#r @"\\psf\Home\Documents\pc\FStat\packages\MathNet.Numerics.2.1.2\lib\Net40\MathNet.Numerics.dll"
#r @"\\psf\Home\Documents\pc\FStat\packages\MathNet.Numerics.FSharp.2.1.2\lib\Net40\MathNet.Numerics.FSharp.dll"
#r @"\\psf\Home\Documents\pc\FStat\packages\MSDN.FSharpChart.dll.0.60\lib\MSDN.FSharpChart.dll"
#r @"\\psf\Home\Documents\pc\FStat\packages\zlib.net.1.0.4.0\lib\zlib.net.dll"
#r @"FSharp.PowerPack, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a19089b1c74d0809"
#r @"mscorlib"
#r @"FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
#r @"System"
#r @"System.Core"
#r @"System.Drawing"
#r @"System.Numerics"
#r @"System.Windows.Forms"
#r @"System.Windows.Forms.DataVisualization"
#load @"\\psf\Home\Documents\pc\FStat\FStat\Program.fs"
#load @"\\psf\Home\Documents\pc\FStat\FStat\Samples\MathNet.Numerics.FSharp\Apply.fs"
#load @"\\psf\Home\Documents\pc\FStat\FStat\Samples\MathNet.Numerics.FSharp\DenseVector.fs"
#load @"\\psf\Home\Documents\pc\FStat\FStat\Samples\MathNet.Numerics.FSharp\Histogram.fs"
#load @"\\psf\Home\Documents\pc\FStat\FStat\Samples\MathNet.Numerics.FSharp\MCMC.fs"
